apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: expensetracker
spec:
  selector:
    matchLabels:
      app: myapp-app
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-app
    spec:
      containers:
      - name: expensetracker
        image: utsavv27/expensetracker:1.0.0 # {"$imagepolicy": "project:gymie"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: app-port
        envFrom:
        - configMapRef:
            name: app-cm
      imagePullSecrets:
      - name: ecr-secret
